Remove unneeded packages
WatWowMap/MapJS pull request #241
Opened 2020-09-30 18:53 UTC by versx

- Removes the `json-merger` package which has a RCE vulnerability that hasn't been fixed still.
- Replaced by native function to merge objects.
- Removes unused `cookie-session` package.

2020-09-30 19:18 UTC, Mygod commented
You sure this does the same thing? Also I think I told you the vuln is nothing serious for mapjs.

2020-09-30 19:27 UTC, versx commented
> You sure this does the same thing? Also I think I told you the vuln is nothing serious for mapjs.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2020-09-30 20:32 UTC, bschultz approved these changes

2020-10-02 13:48 UTC, clburlison commented
Yeah this method doesn't result in the same output. To verify in `config.json`

```
    "map": {
        "startLat": XXXX,
        "startLon": -XXXX,
        "startZoom": 12,
        "minZoom": 10,
        "maxZoom": 18,
        "filters": {
            "gyms": true
        }
    },
```

When you `console.log(target);` you'll see the keys nested keys aren't merged properly.

The deepmerge package does this properly without introducing unsafe deps.

```
npm install deepmerge
```

```
'use strict';

const uConfig = require('../configs/config.json');
const eConfig = require('../configs/default.json');
const merge = require('deepmerge')
const target = merge(eConfig, uConfig);

module.exports = target;
```

2020-10-02 16:26 UTC, bschultz commented
> Yeah this method doesn't result in the same output. To verify in `config.json`
> 
> ```
>     "map": {
>         "startLat": XXXX,
>         "startLon": -XXXX,
>         "startZoom": 12,
>         "minZoom": 10,
>         "maxZoom": 18,
>         "filters": {
>             "gyms": true
>         }
>     },
> ```
> 
> When you `console.log(target);` you'll see the keys nested keys aren't merged properly.
> 
> The deepmerge package does this properly without introducing unsafe deps.
> 
> ```
> npm install deepmerge
> ```
> 
> ```
> 'use strict';
> 
> const uConfig = require('../configs/config.json');
> const eConfig = require('../configs/default.json');
> const merge = require('deepmerge')
> const target = merge(eConfig, uConfig);
> 
> module.exports = target;
> ```

shit, you're right. At first glance it looked good to me. Also overwriting of nested keys works, but somehow nested keys are not merged into target when you just want the default 🤔 
This was something I didn't realized (and approved it) 🙈

2020-10-02 16:30 UTC, bschultz requested changes
Use `deepmerge` package

2020-10-02 16:30 UTC, Mygod commented
Great. Now let's see how long it will take @versx to realize what he is doing.

Also as I said, keep using `jsonmerger`.

2020-10-02 16:51 UTC, bschultz commented
> Great. Now let's see how long it will take @versx to realize what he is doing.
> 
> Also as I said, keep using `jsonmerger`.

Why should we? `deepmerge` does the same without vulns.

We could also just use lodash for this job, as it's already installed as dependency and does the same.

```
const _ = require('lodash');
const target = _.merge(eConfig, uConfig);
```

2020-10-16 04:18 UTC, clburlison approved these changes
Using `extend` works as intended.

2020-10-21 01:01 UTC, merged