Update Grunt Rewards
WatWowMap/MapJS pull request #252
Opened 2020-10-14 16:53 UTC by TurtIeSocks

- Updated Grunt Rewards
- Added Third Encounter
- Formatting

2020-10-15 02:02 UTC, Mygod commented
https://github.com/TurtIeSocks/MapJS/pull/18

2020-10-15 05:44 UTC, versx approved these changes

2020-10-15 05:55 UTC, Mygod approved these changes
Pokestop popup is too long but I can live with it for now.

2020-10-16 04:16 UTC, clburlison requested changes
The pop is now so big it auto closes on smaller phones. The iPhone 7 has a 4.7" screen and can no longer see this information.

2020-10-16 20:01 UTC, TurtIeSocks commented
![image](https://user-images.githubusercontent.com/58572875/96303643-bd601a80-0fc8-11eb-86a0-4a0466027107.png)
![image](https://user-images.githubusercontent.com/58572875/96303691-d1a41780-0fc8-11eb-9c8e-1a873f06a093.png)
![image](https://user-images.githubusercontent.com/58572875/96303496-7c680600-0fc8-11eb-8baa-e461a22600ea.png)

@clburlison @Mygod better?

2020-10-17 01:21 UTC, TurtIeSocks commented
![image](https://user-images.githubusercontent.com/58572875/96325396-66246f00-0ff5-11eb-8627-0d14b11a59e9.png)

Before & After

2020-10-17 01:38 UTC, versx approved these changes

2020-10-17 01:40 UTC, versx commented
> ![image](https://user-images.githubusercontent.com/58572875/96325396-66246f00-0ff5-11eb-8627-0d14b11a59e9.png)
> 
> Before & After

Might be able to reduce it another 10 pixels or so if you delete the double line breaks between `Last Updated` text and the navigation buttons.

2020-10-17 02:27 UTC, clburlison commented
I'm no longer near my laptop so can't test but like the screenshots changes.

2020-10-17 02:28 UTC, clburlison approved these changes
Approving but can't validate the latest changes on a test device.

2020-10-17 02:36 UTC, Mygod commented on static/js/index.js
> +        content += '<center><small><b>Last Updated:</b> ' + updatedDate.toLocaleDateString() + ' ' + updatedDate.toLocaleTimeString() + ' (' + getTimeSince(updatedDate) + ')<br></small></center>';
Avoid using center/small. Use CSS.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

2020-10-17 03:00 UTC, TurtIeSocks commented
![image](https://user-images.githubusercontent.com/58572875/96326935-ec937d80-1002-11eb-9275-15b2906b027b.png)
![image](https://user-images.githubusercontent.com/58572875/96326954-1056c380-1003-11eb-9d17-45243609ee2b.png)
![image](https://user-images.githubusercontent.com/58572875/96326985-52800500-1003-11eb-9275-e9d250983b81.png)

Alright, well before I get too off course with this pr, I cleaned up a few things for quests/invasions. I'll do more cleanup in a later PR. Let me know if everything looks okay and I'll go ahead and merge.

2020-10-17 03:11 UTC, Mygod commented on static/css/index.css
> +.table-invasion td:nth-child(2n) {
`td:nth-child(2)`

2020-10-17 03:11 UTC, Mygod commented on static/css/index.css
> +    padding-left: 13px;
13 is an odd (prime) number... I think 12px will work better on screens with e.g. 150% scale.

2020-10-17 03:11 UTC, Mygod commented on static/css/index.css
> +
uh

2020-10-18 03:09 UTC, merged