Better Role Watching
WatWowMap/MapJS pull request #284
Opened 2020-11-23 05:03 UTC by TurtIeSocks

Clears Discord Member Sessions for:
- guildMemberRemove
- guildMemberUpdate

Currently based on overall map perms. Open to suggestions.

Credits: *Borrowed* from Poracle role manager

2020-11-23 08:30 UTC, versx approved these changes

2020-11-27 23:37 UTC, versx commented on src/services/events/guildMemberUpdate.js
> +    if (roleAfter) after = true;
```suggestion
    let before = oldPresence.roles.cache.find((role) => client.config.discord.perms.map.roles.includes(role.id));
    let after = newPresence.roles.cache.find((role) => client.config.discord.perms.map.roles.includes(role.id));
```
Simplify check

2020-12-01 00:31 UTC, clburlison approved these changes
This works great for removing access from the map. 

As such I'm happy to get this merged in as it stands. However if someone's access gets elevated from basic access (think raids) to paid (pokemon, quests, etc) this currently doesn't solve that use case. Might be worth doing that in another PR as I'm not sure of a quick fix. @TurtIeSocks 's decision on how to move forward.

2020-12-01 01:18 UTC, TurtIeSocks commented
> This works great for removing access from the map.
> 
> As such I'm happy to get this merged in as it stands. However if someone's access gets elevated from basic access (think raids) to paid (pokemon, quests, etc) this currently doesn't solve that use case. Might be worth doing that in another PR as I'm not sure of a quick fix. @TurtIeSocks 's decision on how to move forward.

Hmm could probably write up some more rules in the guildMemberUpdate file.

2020-12-01 03:28 UTC, clburlison requested changes
Try this change. It will reduce the client.config.discord.perms.X.X.roles into a single array. Then anytime one of these roles is added or removed from a member the user session cache will be clear.

2020-12-01 03:28 UTC, clburlison commented on src/services/events/guildMemberUpdate.js
> +        if (roleBefore && !roleAfter) {
```suggestion
    const rolesBefore = oldPresence.roles.cache
                .filter(x => BigInt(x.id).toString())
                .keyArray();
    const rolesAfter = newPresence.roles.cache
                .filter(x => BigInt(x.id).toString())
                .keyArray();
    const perms = Object.values(client.config.discord.perms)
                .map(x => x.roles)
                .reduce(x => [...x]);
    const roleDiff = rolesBefore
                 .filter(x => !rolesAfter.includes(x))
                 .concat(rolesAfter
                    .filter(x => !rolesBefore.includes(x))
                 );
    try {
        if (perms.includes(roleDiff[0])) {
```

2020-12-04 01:32 UTC, TurtIeSocks commented
@clburlison I think we should just merge 🤷

2020-12-04 01:38 UTC, clburlison approved these changes

2020-12-04 14:33 UTC, merged