Fix rockets light mode
WatWowMap/MapJS pull request #292
Opened 2020-11-30 19:18 UTC by TurtIeSocks

Fixes #291 

![image](https://user-images.githubusercontent.com/58572875/100653743-daea0900-3316-11eb-8b19-1a24ca3fe799.png)

![image](https://user-images.githubusercontent.com/58572875/100653774-e76e6180-3316-11eb-9537-290d7a1ff89d.png)

2020-11-30 19:22 UTC, Mygod requested changes
Look at `.theme-dark` or whatever it's called thanks.

2020-11-30 19:33 UTC, Mygod approved these changes

2020-11-30 20:01 UTC, LordJavi approved these changes

2020-12-01 00:04 UTC, clburlison approved these changes

2020-12-01 00:04 UTC, merged