changed Text in variables to be able to translate it
WatWowMap/MapJS pull request #324
Opened 2021-02-11 11:41 UTC by ZombieCorn80

2021-02-11 14:46 UTC, versx approved these changes

2021-02-11 19:13 UTC, TurtIeSocks approved these changes

2021-02-14 22:11 UTC, Mygod approved these changes
Weird indentations but ok.

2021-02-14 22:14 UTC, versx requested changes

2021-02-14 22:14 UTC, versx commented on static/locales/_en.json
> +               "filter_option_form": "By Form"
```suggestion
    "filter_option_rarity": "By Rarity",
    "filter_option_generation": "By Generation",
    "filter_option_form": "By Form"
```

2021-02-14 22:15 UTC, versx requested changes

2021-02-14 22:15 UTC, versx commented on static/locales/_en.json
> +    "filter_option_form": "By Form"
```suggestion
	"filter_option_rarity": "By Rarity",
	"filter_option_generation": "By Generation",
	"filter_option_form": "By Form"
```

2021-02-14 22:16 UTC, versx approved these changes

2021-02-20 21:06 UTC, merged