Hide Individual Quests
WatWowMap/MapJS pull request #336
Opened 2021-03-06 18:45 UTC by versx

![image](https://user-images.githubusercontent.com/1327440/110217476-ff4f0780-7e68-11eb-948f-00707a82064f.png)

2021-03-11 00:00 UTC, TurtIeSocks requested changes

2021-03-11 00:25 UTC, versx commented on static/js/index.js
> +            <td><a title="Filter Quest" href="#" onclick="addQuestFilter(${JSON.stringify(questReward.info)}, false);return false;"><b>[Exclude]</b></a></td>
Interesting, I didn't experience that but will commit the suggestion non-the-less

2021-03-11 00:35 UTC, TurtIeSocks approved these changes

2021-03-11 00:58 UTC, Mygod commented on static/js/index.js
> +            <td><a title="Filter Quest" href="#" onclick="addQuestFilter(${JSON.stringify(questReward.info)}, false);return false;"><b>[Exclude]</b></a></td>
Because JSON uses double quotes.

2021-03-11 00:59 UTC, Mygod commented
I have a separate comment. When there is both quests and invasions on the stop, it is not clear if you are excluding/hiding quests or invasions.

2021-03-16 00:27 UTC, versx commented
> I have a separate comment. When there is both quests and invasions on the stop, it is not clear if you are excluding/hiding quests or invasions.

That's a good point, I'll update the text

2021-04-02 02:03 UTC, merged