Support Popup Translations
WatWowMap/MapJS pull request #356
Opened 2021-04-08 17:45 UTC by TurtIeSocks

- All popups are now translatable
- Some additional menus as well
- Changed most popups to use `` instead of ''

2021-04-08 21:14 UTC, lenisko requested changes
one wrongly picked key

2021-04-08 21:30 UTC, TurtIeSocks commented on static/js/index.js
> +                content += `<b>${i18n('gym_last_seen_in_battle')}!</b><br>`;
Resolved in following commit, thanks!

2021-04-09 00:58 UTC, versx approved these changes
Hell yeah, nice job!

2021-04-09 01:16 UTC, lenisko requested changes

2021-04-09 01:16 UTC, lenisko commented on src/views/index.mustache
> +                            {{iv_range}}: <kbd>90-100</kbd> - {{iv_example}}<br>
`iv_example` is a bit confusing as a name as it's not an example. What about `iv_example_help` or `iv_explanation` ? (same for others).

2021-04-09 01:16 UTC, lenisko commented on static/locales/_en.json
> +    "or": "or",
`NOT` and help strings logic gates are already upper case. Lets make them all upper.

Small bonus with `On` and `Off`. 

It's much easier to read them like that I think.
```
    "filter_and": "And",
    "filter_or": "Or",
    "filter_on": "On",
    "filter_off": "Off",
    "or": "or",
```

2021-04-09 20:36 UTC, lenisko approved these changes

2021-04-15 01:09 UTC, versx approved these changes

2021-04-15 01:09 UTC, versx approved these changes

2021-04-15 01:10 UTC, versx approved these changes

2021-04-15 02:29 UTC, lenisko commented
So important that @versx approved it 3 times in row! (and 4 in total 😂)

2021-04-15 14:29 UTC, merged